# name: Deploy React App

# on:
#   push:
#     branches:
#       - main  # Runs workflow on push to main branch

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and Push Docker Image
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           push: true
#           tags: prince1005/inventory1:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - name: SSH into Server and Deploy
#         uses: appleboy/ssh-action@v0.1.4
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           password: ${{ secrets.SERVER_PASSWORD }}
#           script: |
#             docker pull prince1005/inventory1:latest
#             docker stop inventory1 || true
#             docker rm inventory1 || true
#             docker run -d -p 80:80 --name inventory1 prince1005/inventory1:latest


name: Auto Build & Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t prince1005/inventory1 .
          docker push prince1005/inventory1
